### ISSUE TITLE
isolib: output is invalid if using 10% intensity cutoff

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#651]
This seems to happen if the cutoff is larger than 1, see this file for reference: https://galaxy-umsa.grid.cesnet.cz/api/datasets/6cc7f8ceef4b312f/display?to_ext=tabular

The R script for the tool is available here: https://github.com/RECETOX/galaxytools/blob/master/tools/isolib/isolib.R

**Comment by hechth** [comment]
Running the galaxy tool for isolib with a 10% intensity cutoff results in this file:
[Galaxy34-\[isolib on data 33\].txt](https://github.com/user-attachments/files/20066096/Galaxy34-.isolib.on.data.33.txt)

**Comment by hechth** [comment]
Turns out this is related to how the threshold parameter is used in the enviPat package and it just needs to be used correctly.

**Comment by hechth** [comment]
Example input: https://galaxy-umsa.grid.cesnet.cz/api/datasets/8c525cca26d25368/display?to_ext=tabular

**Comment by acquayefrank** [comment]
I have pushed the changes(improvements). However, I don't think this "bug" can be fully resolved as it has more to do with user input. e.g. I can choose a rel_to value of 2 and a threshold value of  0.0005. Per the documentation, this is a valid set of inputs but may yield the error described due to the fact that the threshold chosen is really low. So, I tried to add as much help as possible to aid users in picking the correct values. 

Please let me know if I have missed anything.

**Comment by hechth** [comment]
The bug still remains - I guess we should divide the user input if it is between 0 - 100 by 100 to scale it to 0 - 1
